List<String> getPlayers() {
  List<String> players = [];
  players.add("Benzema");
  players.add("Neymar");
  players.add("De Bruyne");
  players.add("Kane");
  players.add("Mbappé");
  players.add("Messi");
  players.add("Ronaldo");
  players.add("Lewandowski");
  players.add("Lukaku");
  players.add("Modrić");
  players.add("Vinicius Jr.");
  players.add("Son Heung-Min");
  players.add("Fernandes");
  players.add("Griezmann");
  players.add("Havertz");
  players.add("Mané");
  players.add("Silva");
  players.add("Richarlinson");
  players.add("de Jong");
  players.add("Dembélé");
  players.add("Foden");
  players.add("Giroud");
  players.add("Jesus");
  players.add("Morata");
  players.add("Nuñez");
  players.add("Sané");
  players.add("Félix");
  players.add("Suárez L.");
  players.add("Valverde");
  players.add("Werner");
  players.add("Bellingham");
  players.add("Bergwijn");
  players.add("Leão");
  players.add("Eriksen");
  players.add("Di María");
  players.add("Raphinha");
  players.add("Gnabry");
  players.add("Hazard E.");
  players.add("Janssen");
  players.add("Kramarić");
  players.add("Pedri");
  players.add("Lautaro");
  players.add("Müller");
  players.add("Musiala");
  players.add("Gavi");
  players.add("Saka");
  players.add("Torres F.");
  players.add("Batshuayi");
  players.add("Damsgaard");
  players.add("Antony");
  players.add("Gakpo");
  players.add("Grealish");
  players.add("Kimmich");
  players.add("Mitrović A.");
  players.add("Nkunku");
  players.add("Skov Olsen");
  players.add("Perišić");
  players.add("Sterling");
  players.add("Vlahović");
  players.add("Abraham");
  players.add("Asensio");
  players.add("Bale");
  players.add("Bentancur");
  players.add("Berghuis");
  players.add("Brobbey");
  players.add("Camavinga");
  players.add("Correa A.");
  players.add("Davies");
  players.add("de Paul");
  players.add("Dolberg");
  players.add("Embolo");
  players.add("Carrasco");
  players.add("Gravenberch");
  players.add("Gündoğan");
  players.add("Iglesias");
  players.add("Kolo Muani");
  players.add("Kovačić");
  players.add("Lo Celso");
  players.add("Lozano");
  players.add("Martinelli");
  players.add("Milinković-Savić S.");
  players.add("Mount");
  players.add("Sarabia");
  players.add("Soler");
  players.add("Tadić");
  players.add("Tchouaméni");
  players.add("Tielemans");
  players.add("Paquetá");
  players.add("Trossard");
  players.add("Xhaka");
  players.add("Ziyech");
  players.add("Álvarez E.");
  players.add("Brozović");
  players.add("Casimiro");
  players.add("Neves");
  players.add("David");
  players.add("Delaney");
  players.add("Diatta");
  players.add("Doku");
  players.add("Pino");
  players.add("Jović");
  players.add("Klaassen");
  players.add("Kostić");
  players.add("Vitinha");
  players.add("Mertens");
  players.add("Nmecha");
  players.add("Koke");
  players.add("Sarr");
  players.add("Shaqiri");
  players.add("Rodrygo");
  players.add("Williams I.");
  players.add("Zakaria");
  players.add("Álvarez");
  players.add("Marquinhos");
  players.add("Arnold");
  players.add("Braithwaite");
  players.add("Budimir");
  players.add("Busquets");
  players.add("Cancelo");
  players.add("De la Cruz");
  players.add("de Roon");
  players.add("Dia");
  players.add("Dumfries");
  players.add("En-Nesyri");
  players.add("Freuler");
  players.add("Guimarães");
  players.add("Harit");
  players.add("Hazard T.");
  players.add("Henderson");
  players.add("Rodri");
  players.add("Hofmann");
  players.add("Højbjerg");
  players.add("Ilić I.");
  players.add("James");
  players.add("Jiménez");
  players.add("Johnson");
  players.add("Kamada");
  players.add("Kimpembe");
  players.add("Livaja");
  players.add("Llorente M.");
  players.add("Milik");
  players.add("Minamino");
  players.add("Openda");
  players.add("Oršić");
  players.add("Paredes");
  players.add("Pašalić");
  players.add("Petković");
  players.add("Phillips");
  players.add("Piątek");
  players.add("Rice");
  players.add("Fred");
  players.add("Rodríguez");
  players.add("Dias");
  players.add("Seferović");
  players.add("Carvalho");
  players.add("Taremi");
  players.add("Taylor");
  players.add("Toney");
  players.add("van Dijk");
  players.add("Varane");
  players.add("Vargas");
  players.add("Walker");
  players.add("Weghorst");
  players.add("Williams N.");
  players.add("Witsel");
  players.add("Zalewski");
  players.add("Zieliński");
  players.add("Aaronson");
  players.add("Pedro");
  players.add("Adams");
  players.add("Akanji");
  players.add("Aké");
  players.add("Alba");
  players.add("Alexander-Arnold");
  players.add("Araujo");
  players.add("Atkinson");
  players.add("Azmoun");
  players.add("Alisson");
  players.add("Boufal");
  players.add("Bowen");
  players.add("Caicedo");
  players.add("Carvajal");
  players.add("Ciss");
  players.add("Correa J.");
  players.add("Courtois");
  players.add("Silva");
  players.add("De Ketelaere");
  players.add("de Ligt");
  players.add("Dendoncker");
  players.add("Dieng B.");
  players.add("Duke");
  players.add("Munir");
  players.add("Fernández");
  players.add("Torres P.");
  players.add("Frankowski");
  players.add("Militão");
  players.add("Giménez J.");
  players.add("Gómez");
  players.add("Guardado");
  players.add("Guendouzi");
  players.add("Gvardiol");
  players.add("Hakimi");
  players.add("Hwang Hee-Chan");
  players.add("Irvine");
  players.add("Ito J.");
  players.add("James");
  players.add("Jensen");
  players.add("Kamiński");
  players.add("Koulibaly");
  players.add("Koundé");
  players.add("Kubo");
  players.add("Leckie");
  players.add("Lloris");
  players.add("Palhinha");
  players.add("Lukić");
  players.add("Mac Allister");
  players.add("Majer");
  players.add("Martínez D.");
  players.add("Martínez Lis.");
  players.add("Matondo");
  players.add("Mbeumo");
  players.add("McKennie");
  players.add("Mendes");
  players.add("Meunier");
  players.add("Mitoma");
  players.add("Mooy");
  players.add("Onana");
  players.add("Mæhle");
  players.add("Mário");
  players.add("Neuer");
  players.add("Nunes");
  players.add("Partey");
  players.add("Pavard");
  players.add("Pellistri");
  players.add("Pickford");
  players.add("Reyna");
  players.add("Roberts");
  players.add("Rüdiger");
  players.add("Saliba");
  players.add("Simon");
  players.add("Sow");
  players.add("Stones");
  players.add("Szymański");
  players.add("Fabinho");
  players.add("Telles");
  players.add("Timber");
  players.add("Tomiyasu");
  players.add("Torreira");
  players.add("Trippier");
  players.add("Upamecano");
  players.add("Vanaken");
  players.add("Vecino");
  players.add("Vega");
  players.add("Veretout");
  players.add("Vlašić");
  players.add("Ward-Prowse");
  players.add("Wind");
  players.add("Żurkowski");
  players.add("Đuričić");
  players.add("Aboubakar");
  players.add("Alderweireld");
  players.add("Tagliafico");
  players.add("Almada");
  players.add("Alvarado");
  players.add("Alves");
  players.add("Amrabat");
  players.add("Ansarifard");
  players.add("Eustáquio");
  players.add("Asano");
  players.add("Ayew J.");
  players.add("Azpilicueta");
  players.add("Badiashile");
  players.add("Blind");
  players.add("Botman");
  players.add("Boyle");
  players.add("Bremer");
  players.add("Cáceres S.");
  players.add("Cáceres M.");
  players.add("Canobbio");
  players.add("Castagne");
  players.add("Chilwell");
  players.add("Christensen A.");
  players.add("Colwill");
  players.add("Cornelius");
  players.add("Danilo");
  players.add("Dalot");
  players.add("de Vrij");
  players.add("Dest");
  players.add("Dier");
  players.add("Doan");
  players.add("Patrício");
  players.add("Endo");
  players.add("Estrada");
  players.add("Fofana");
  players.add("Gayá");
  players.add("Gholizadeh");
  players.add("Gosens");
  players.add("Grosicki");
  players.add("Gudelj");
  players.add("Gueye I.");
  players.add("Gueye P.");
  players.add("Gutiérrez");
  players.add("Pereira");
  players.add("Herrera");
  players.add("Horta");
  players.add("Hrustic");
  players.add("Itakura");
  players.add("Ito H.");
  players.add("Jahanbakhsh");
  players.add("Jakić");
  players.add("Jeong");
  players.add("Kehrer");
  players.add("Kim Min-Jae");
  players.add("Klich");
  players.add("Kouyaté");
  players.add("Kristensen");
  players.add("Krychowiak");
  players.add("Kudus");
  players.add("Larin");
  players.add("Lee Kang-In");
  players.add("Levitt");
  players.add("Lindstrøm");
  players.add("Linetty");
  players.add("Livaković");
  players.add("Llorente D.");
  players.add("Lovren");
  players.add("MacLaren");
  players.add("Maksimović");
  players.add("Malacia");
  players.add("Martín");
  players.add("Mazraoui");
  players.add("Costa");
  players.add("Mendy");
  players.add("Mendy");
  players.add("Milinković-Savić V.");
  players.add("Mmaee R.");
  players.add("Molina");
  players.add("Moore");
  players.add("Morita");
  players.add("N'Koudou");
  players.add("Navas");
  players.add("Ochoa");
  players.add("Okafor");
  players.add("Otamendi");
  players.add("Ounahi");
  players.add("Pasveer");
  players.add("Pavlović");
  players.add("Pope");
  players.add("Radonjić");
  players.add("Raum");
  players.add("Roberts");
  players.add("Rochet");
  players.add("Romero");
  players.add("Rulli");
  players.add("Salisu");
  players.add("Sánchez E.");
  players.add("Sandro");
  players.add("Ederson");
  players.add("Sargent");
  players.add("Satriano");
  players.add("Schlotterbeck");
  players.add("Schmeichel");
  players.add("Shaw");
  players.add("Rui");
  players.add("Smith");
  players.add("Sommer");
  players.add("Stanisic");
  players.add("Steffen");
  players.add("Sučić");
  players.add("Süle");
  players.add("Sulemana");
  players.add("Świderski");
  players.add("Szczęsny");
  players.add("ter Stegen");
  players.add("Kjær");
  players.add("Toko Ekambi");
  players.add("Tomori");
  players.add("Turner");
  players.add("Ueda");
  players.add("Varela");
  players.add("Vertonghen");
  players.add("Williams");
  players.add("Aboukhlal");
  players.add("Acosta");
  players.add("Aebischer");
  players.add("Afena-Gyan");
  players.add("Al-Dawsari S.");
  players.add("Al-Muwallad");
  players.add("Álvarez");
  players.add("Álvarez K.");
  players.add("Amallah");
  players.add("Amartey");
  players.add("Andersen");
  players.add("Angulo");
  players.add("Antuna");
  players.add("Araújo");
  players.add("Areola");
  players.add("Arriola");
  players.add("Ayew A.");
  players.add("Baba A.");
  players.add("Baba I.");
  players.add("Babić");
  players.add("Ballo-Touré");
  players.add("Barišić");
  players.add("Bednarek");
  players.add("Behich");
  players.add("Belhanda");
  players.add("Bella-Kotchap");
  players.add("Bennette");
  players.add("Borjan");
  players.add("Bounou");
  players.add("Burns");
  players.add("Campbell");
  players.add("Cash");
  players.add("Castelletto");
  players.add("Cavallini");
  players.add("Chair");
  players.add("Chávez");
  players.add("Cho Yu-Min");
  players.add("Cifuentes");
  players.add("Cillessen");
  players.add("Coady");
  players.add("Coates");
  players.add("Dari");
  players.add("De Arrascaeta");
  players.add("Ribeiro");
  players.add("de la Torre");
  players.add("Vitoria");
  players.add("Djiku");
  players.add("Dmitrović");
  players.add("Duarte");
  players.add("Estupiñán");
  players.add("Ez Abde");
  players.add("Fassnacht");
  players.add("Fernandes");
  players.add("Ferreira");
  players.add("Frimpong");
  players.add("Galíndez");
  players.add("Gallardo");
  players.add("García");
  players.add("Giménez");
  players.add("Ginter");
  players.add("Glik");
  players.add("Guehi");
  players.add("Guillamón");
  players.add("Harris");
  players.add("Henderson");
  players.add("Hennessey");
  players.add("Henrichs");
  players.add("Hincapié");
  players.add("Hongla");
  players.add("Hwang In-Beom");
  players.add("Hwang Ui-jo");
  players.add("Ibarra");
  players.add("Issahaku");
  players.add("Ivušić");
  players.add("Jackson");
  players.add("James");
  players.add("Jasari");
  players.add("Jaziri");
  players.add("Juranović");
  players.add("Kawashima");
  players.add("Kaye");
  players.add("Khazri");
  players.add("Kim Seung-Gyu");
  players.add("King");
  players.add("Kiwior");
  players.add("Kobel");
  players.add("Kuol");
  players.add("Kyereh");
  players.add("Laïdouni");
  players.add("Lainez");
  players.add("Lazović");
  players.add("Lee Jae-Sung");
  players.add("Maguire");
  players.add("Malong");
  players.add("Mašović");
  players.add("McKenzie");
  players.add("Mejbri");
  players.add("Mena");
  players.add("Mendy N.");
  players.add("Mignolet");
  players.add("Miller");
  players.add("Mitrović S.");
  players.add("Mitrovic");
  players.add("Mladenović");
  players.add("Montes");
  players.add("Morris");
  players.add("Msakni");
  players.add("Muslera");
  players.add("Nagatomo");
  players.add("Ndiaye");
  players.add("Ngamaleu");
  players.add("Niakhate");
  players.add("Nourollahi");
  players.add("Nsamé");
  players.add("Ntcham");
  players.add("Ocampo");
  players.add("Odoi");
  players.add("Ofori");
  players.add("Olivera");
  players.add("Onana");
  players.add("Oviedo");
  players.add("Pepi");
  players.add("Piette");
  players.add("Piotrowski");
  players.add("Plata");
  players.add("Račić");
  players.add("Ramsdale");
  players.add("Reasco");
  players.add("Rodríguez");
  players.add("Rodríguez");
  players.add("Rogel");
  players.add("Rossi");
  players.add("Ryan");
  players.add("Sabiri");
  players.add("Saïss");
  players.add("Sarr");
  players.add("Schär");
  players.add("Schmidt");
  players.add("Seck");
  players.add("Shibasaki");
  players.add("Skhiri");
  players.add("Skóraś");
  players.add("Slimane");
  players.add("Sliti");
  players.add("Son Jun-Ho");
  players.add("Souttar");
  players.add("Suárez D.");
  players.add("Szymański");
  players.add("Taniguchi");
  players.add("Terzić");
  players.add("Thomas");
  players.add("Tillman");
  players.add("Trapp");
  players.add("Truffert");
  players.add("Ugarte");
  players.add("Ugbo");
  players.add("Valencia E.");
  players.add("Veljkovic");
  players.add("Vida");
  players.add("Vines");
  players.add("Wass");
  players.add("Williams");
  players.add("Wright");
  players.add("Yedlin");
  players.add("Yoshida");
  players.add("Živković");
  players.add("Godin");
  players.add("Alaaeldin");
  players.add("Abdi");
  players.add("Abdulhamid");
  players.add("Almoez Ali");
  players.add("Hatem");
  players.add("Abdulsallam");
  players.add("Waed");
  players.add("Abedzadeh");
  players.add("Adekugbe");
  players.add("Afif");
  players.add("Afriyie");
  players.add("Aguilera");
  players.add("Ahmed");
  players.add("Aidoo");
  players.add("Al-Abid");
  players.add("Al-Amri");
  players.add("Al-Dawsari N.");
  players.add("Al-Faraj");
  players.add("Al-Ghanam");
  players.add("Hassan");
  players.add("Al-Hassan");
  players.add("Al-Heidos");
  players.add("Al-Naji");
  players.add("Al-Owais");
  players.add("Al-Qarni");
  players.add("Al-Rawi");
  players.add("Al Rubaie");
  players.add("Al-Shahrani");
  players.add("Al-Sheeb");
  players.add("Al-Tambakti");
  players.add("Al-Aqidi");
  players.add("Al-Breik");
  players.add("Al-Hadhrami");
  players.add("Albirakan");
  players.add("Albulayhi");
  players.add("Alvarado");
  players.add("Amiri");
  players.add("Ampadu");
  players.add("Angulo");
  players.add("Armani");
  players.add("Arreaga");
  players.add("Arteaga");
  players.add("Attiyat-Allah");
  players.add("Babhir");
  players.add("Baccus");
  players.add("Bakker");
  players.add("Bamsaud");
  players.add("Barnes");
  players.add("Barsham");
  players.add("Baumann");
  players.add("Ben Ouannes");
  players.add("Ben Said");
  players.add("Bereszyński");
  players.add("Bijlow");
  players.add("Bochniewicz");
  players.add("Borges");
  players.add("Boudiaf");
  players.add("Bronn");
  players.add("Brym");
  players.add("Bueno");
  players.add("Bukari");
  players.add("Cabango");
  players.add("Cabrera");
  players.add("Calvo");
  players.add("Cannon");
  players.add("Casteels");
  players.add("Castillo");
  players.add("Chacón");
  players.add("Chalali");
  players.add("Cho Young-Wook");
  players.add("Christensen O.");
  players.add("Cissé");
  players.add("Clauss");
  players.add("Cömert");
  players.add("Contreras");
  players.add("Cornelius");
  players.add("Ró-Ró");
  players.add("Cota");
  players.add("Crépeau");
  players.add("Cummings");
  players.add("Dahmen");
  players.add("Dawidowicz");
  players.add("De Amores");
  players.add("Johnny");
  players.add("Debast");
  players.add("Debchi");
  players.add("Degenek");
  players.add("Delgado");
  players.add("Deng");
  players.add("Deschamps");
  players.add("Devlin");
  players.add("Diallo");
  players.add("Diaw");
  players.add("Dieng T.");
  players.add("Domínguez");
  players.add("Dräger");
  players.add("Drągowski");
  players.add("Ebrahimi");
  players.add("El Djebali");
  players.add("El Yamiq");
  players.add("Elvedi");
  players.add("Emad");
  players.add("Djaló");
  players.add("Epassy");
  players.add("Eraković");
  players.add("Erlić");
  players.add("Espino");
  players.add("Ezatolahi");
  players.add("Faes");
  players.add("Fai");
  players.add("Flekken");
  players.add("Franco");
  players.add("Frei");
  players.add("Fuller");
  players.add("Funes Mori");
  players.add("Ghandri");
  players.add("Ghoddos");
  players.add("Gomis");
  players.add("Gonda");
  players.add("González");
  players.add("Gonzalez");
  players.add("Goodwin");
  players.add("Grabara");
  players.add("Grbić");
  players.add("Gruezo");
  players.add("Gumny");
  players.add("Gunter");
  players.add("Haitham");
  players.add("Hajsafi");
  players.add("Hardani");
  players.add("Harris");
  players.add("Fadel");
  players.add("Hassan");
  players.add("Helik");
  players.add("Hernández");
  players.add("Hoilett");
  players.add("Hong");
  players.add("Horvath");
  players.add("Hosseini M.");
  players.add("Hosseini H.");
  players.add("Ifa");
  players.add("Ilić M.");
  players.add("Jabrane");
  players.add("Jakobs");
  players.add("Jalali");
  players.add("Jebali");
  players.add("Jędrzejczyk");
  players.add("Khoder");
  players.add("Johnson");
  players.add("Johnston");
  players.add("Jung");
  players.add("Onana");
  players.add("Kanani");
  players.add("Kanoo");
  players.add("Karačić");
  players.add("Karbownik");
  players.add("Kędziora");
  players.add("Kennedy");
  players.add("Khalilzadeh");
  players.add("Khaoui");
  players.add("Khenissi");
  players.add("Khoukhi");
  players.add("Kim Dong-Jun");
  players.add("Kim Jin-Su");
  players.add("Kim Moon-Hwan");
  players.add("Kim Tae-Hwan");
  players.add("Kim Young-Gwon");
  players.add("King");
  players.add("Ambrosius");
  players.add("Köhn");
  players.add("Koleosho");
  players.add("Königsdörffer");
  players.add("Kun");
  players.add("Kwon Kyung-Won");
  players.add("Kwon Chang-Hoon");
  players.add("Lafont");
  players.add("Lamptey");
  players.add("Laryea");
  players.add("Leno");
  players.add("León");
  players.add("Long");
  players.add("Lopes");
  players.add("López");
  players.add("Ltaief");
  players.add("Sanchez");
  players.add("Maâloul");
  players.add("Mabil");
  players.add("Machino");
  players.add("Madu");
  players.add("Maeda");
  players.add("Majecki");
  players.add("Sá");
  players.add("Mandanda");
  players.add("Mandjeck");
  players.add("Martínez");
  players.add("Matarrita");
  players.add("Mathlouthi");
  players.add("Mazeed");
  players.add("Mbaizo");
  players.add("McGree");
  players.add("Medina");
  players.add("Mele");
  players.add("Méndez");
  players.add("Méndez");
  players.add("Mendy F.");
  players.add("Mensah");
  players.add("Mepham");
  players.add("Millar");
  players.add("Mmaee S.");
  players.add("Mohammad");
  players.add("Mohammadi");
  players.add("Munir");
  players.add("Moharrami");
  players.add("Montiel");
  players.add("Moreno");
  players.add("Moufi");
  players.add("Moustafa");
  players.add("Muntari");
  players.add("N'Koulou");
  players.add("Na");
  players.add("Name");
  players.add("Nawrocki");
  players.add("Ndiaye");
  players.add("Nelsson");
  players.add("Ngapandouetnbu");
  players.add("Niazmand");
  players.add("Noorafkan");
  players.add("Noppert");
  players.add("Norrington-Davies");
  players.add("Nurudeen");
  players.add("Olaza");
  players.add("Olveira");
  players.add("Omlin");
  players.add("Ondoua");
  players.add("Oum Gouet");
  players.add("Owusu");
  players.add("Pacho");
  players.add("Paik");
  players.add("Palacios");
  players.add("Palmer-Brown");
  players.add("Pereira");
  players.add("Weverton");
  players.add("Pérez");
  players.add("Pezzella");
  players.add("Pineda");
  players.add("Piquerez");
  players.add("Porozo");
  players.add("Pouraliganji");
  players.add("Preciado");
  players.add("Puchacz");
  players.add("Asad");
  players.add("Ramírez");
  players.add("Raya");
  players.add("Reca");
  players.add("Redmayne");
  players.add("Rekik");
  players.add("Rensch");
  players.add("Rezaeian");
  players.add("Rieder");
  players.add("Rodon");
  players.add("Rodríguez");
  players.add("Romo");
  players.add("Rowles");
  players.add("Ruiz");
  players.add("Beiranvand");
  players.add("Sakai");
  players.add("Salas");
  players.add("Salman");
  players.add("Sánchez J.");
  players.add("Sarlak");
  players.add("Sarmiento");
  players.add("Sassi");
  players.add("Scally");
  players.add("Scaloni");
  players.add("Semenyo");
  players.add("Sequiera");
  players.add("Sharahili");
  players.add("Silva");
  players.add("Skorupski");
  players.add("Soma");
  players.add("Song");
  players.add("Sosa");
  players.add("Sosa");
  players.add("Southgate");
  players.add("St Clair");
  players.add("Struijk");
  players.add("Stryger Larsen");
  players.add("Šutalo");
  players.add("Tagnaouti");
  players.add("Talavera");
  players.add("Talbi");
  players.add("Tanaka");
  players.add("Tawamba");
  players.add("Tchato");
  players.add("Tejeda");
  players.add("Theate");
  players.add("Tite");
  players.add("Tolo");
  players.add("Torabi");
  players.add("Torres");
  players.add("Valencia A.");
  players.add("Valery");
  players.add("Valle");
  players.add("Van de Ven");
  players.add("Vargas");
  players.add("Vásquez");
  players.add("Venegas");
  players.add("Viña");
  players.add("Vukovic");
  players.add("Ward");
  players.add("Waston");
  players.add("Waterman");
  players.add("Widmer");
  players.add("Wieteska");
  players.add("Wilson");
  players.add("Wollacott");
  players.add("Wooh");
  players.add("Yamane");
  players.add("Yang");
  players.add("Yongwa");
  players.add("Yoon");
  players.add("Zakaria");
  players.add("Zamora");
  players.add("Zimmerman");
  players.add("Luis Enrique");
  players.add("Flick");
  players.add("van Gaal");
  players.add("Hjulmand");
  players.add("Martinez");
  players.add("Santos");
  players.add("Alonso");
  players.add("Cissé");
  players.add("Dalic");
  players.add("Stojkovic");
  players.add("Yakin");
  players.add("Alfaro");
  players.add("Berhalter");
  players.add("Martino");
  players.add("Michniewicz");
  players.add("Page");
  players.add("Addo");
  players.add("Bento");
  players.add("Moriyasu");
  players.add("Quieroz");
  players.add("Regragui");
  players.add("Song");
  players.add("Arnold");
  players.add("Suarez");
  players.add("Herdman");
  players.add("Kadri");
  players.add("Renard");
  players.add("Sanchez Bas");

  return players;
}